# Generated by Django 3.2.18 on 2023-04-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_tag_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='descriptions',
            new_name='description',
        ),
    ]
